### ISSUE TITLE
Attack of Opportunity range

### ISSUE THREAD

**Issue by Ozymandias-I** [reyzor1991/pf2e-automations#11]
I'm playing using the Metric System, but I don't know if it is possible to change Attack of Opportunity range in this module. In a combat it counts each square as 5 foot even with me changing the grid value.

**Comment by reyzor1991** [comment]
Not sure that pf2e correct works with other metric system. Because units in settings  it's only text

actor not have info about other distance units only value

default are 5 for base and 5 for manipulate
