### ISSUE TITLE
Focus Points deducted twice

### ISSUE THREAD

**Issue by Keatnisher** [reyzor1991/pf2e-automations#13]
Hi,

When using fortissimo or lingering composition, focus points are deducted twice. Once when clicking cast (system does this) and again when the automations take place.

Not sure if this occurs elsewhere (spell slots maybe?).

**Comment by reyzor1991** [comment]
This is correct because for fortissimo or lingering composition need to post message instead of click cast

These spells have specific logic - on failure not decrease Focus Points
