### ISSUE TITLE
Other Categorization

### ISSUE THREAD

**Issue by Nykraser** [reyzor1991/pf2e-automations#15]
When creating custom new rules, if they don't fall into one of your auto sort categories they do not appear in the other tab on the new UI.
The rules continue to work if they were made correctly but there is no way to view, edit, or disable the rules in the UI.
For example if you use "triggerType": "initiative" to make a rule it will not appear in any of the tabs but the rule will function.
I believe that this is due to an issue with the way you defined the "other" category causing it to not actually have everything that doesn't fall into the auto sort.

**Comment by reyzor1991** [comment]
Fix next release
