### ISSUE TITLE
Maybe not an Issue but "Knockdown" is missing.

### ISSUE THREAD

**Issue by liquidsonic** [reyzor1991/pf2e-automations#4]
I noticed when running through some mock game stuff that Knockdown wasn't on your list.

![image](https://github.com/user-attachments/assets/19a23de7-8fbd-42b4-bcec-d61786f1f565)
![image](https://github.com/user-attachments/assets/9021a5e8-d13c-49f8-81ae-5c4be97cfc53)

**Comment by reyzor1991** [comment]
Knockdown is macro

https://foundryvtt.com/packages/pf2e-macros

**Comment by liquidsonic** [comment]
Apologies,

It wasn't clear from the image. This is an NPC.

Was referring to the triggers that prompt when you roll a strike with the correspond action attached to them such as grab, improved grab, knockdown etc.

I couldn't see it in the lists.

**Comment by reyzor1991** [comment]
For NPC attack Effects only grab and improved grab are implemented

**Comment by liquidsonic** [comment]
Ah okay, so it's just not done yet. Apologies then.
