### ISSUE TITLE
[Feature] Ability to Export a Single Rule

### ISSUE THREAD

**Issue by ChasarooniZ** [reyzor1991/pf2e-automations#8]
IF individual rules could be exported then it'd make it easier to add them to the list of rules

**Comment by ChasarooniZ** [comment]
Also if there were some way to break up the json (in the repo before it gets combined into one rule) based on names then people could contribute to the list a bit easier

**Comment by reyzor1991** [comment]
In next release I will add import for 1 rule 
and folder where need to save rules by files

**Comment by ChasarooniZ** [comment]
<3
